vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       article_images:
            uri_prefix: /uploads/article
            upload_destination: '%kernel.project_dir%/public/uploads/article'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true